// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

/*
Package api ...
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HTTPError ...
type HTTPError struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPError) Reset()         { *m = HTTPError{} }
func (m *HTTPError) String() string { return proto.CompactTextString(m) }
func (*HTTPError) ProtoMessage()    {}
func (*HTTPError) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_30eca53ec2c6461a, []int{0}
}
func (m *HTTPError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPError.Unmarshal(m, b)
}
func (m *HTTPError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPError.Marshal(b, m, deterministic)
}
func (dst *HTTPError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPError.Merge(dst, src)
}
func (m *HTTPError) XXX_Size() int {
	return xxx_messageInfo_HTTPError.Size(m)
}
func (m *HTTPError) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPError.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPError proto.InternalMessageInfo

func (m *HTTPError) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HTTPError) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// Error ...
type Error struct {
	Message              string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Errors               []*FieldErr `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_30eca53ec2c6461a, []int{1}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetErrors() []*FieldErr {
	if m != nil {
		return m.Errors
	}
	return nil
}

// FieldErr ...
type FieldErr struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Errors               []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldErr) Reset()         { *m = FieldErr{} }
func (m *FieldErr) String() string { return proto.CompactTextString(m) }
func (*FieldErr) ProtoMessage()    {}
func (*FieldErr) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_30eca53ec2c6461a, []int{2}
}
func (m *FieldErr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldErr.Unmarshal(m, b)
}
func (m *FieldErr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldErr.Marshal(b, m, deterministic)
}
func (dst *FieldErr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldErr.Merge(dst, src)
}
func (m *FieldErr) XXX_Size() int {
	return xxx_messageInfo_FieldErr.Size(m)
}
func (m *FieldErr) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldErr.DiscardUnknown(m)
}

var xxx_messageInfo_FieldErr proto.InternalMessageInfo

func (m *FieldErr) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *FieldErr) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*HTTPError)(nil), "api.HTTPError")
	proto.RegisterType((*Error)(nil), "api.Error")
	proto.RegisterType((*FieldErr)(nil), "api.FieldErr")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_30eca53ec2c6461a) }

var fileDescriptor_api_30eca53ec2c6461a = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x72, 0xe4, 0xe2, 0xf4, 0x08,
	0x09, 0x09, 0x70, 0x2d, 0x2a, 0xca, 0x2f, 0x12, 0x12, 0xe2, 0x62, 0x49, 0xce, 0x4f, 0x49, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0xb3, 0x85, 0x14, 0xb8, 0x58, 0x53, 0x41, 0x92, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x5c, 0x7a, 0x20, 0x03, 0xc0, 0xca, 0x83, 0x20, 0x12, 0x4a,
	0x1e, 0x5c, 0xac, 0x10, 0xed, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0x10, 0x13,
	0x38, 0x83, 0x60, 0x5c, 0x21, 0x55, 0x2e, 0x36, 0xb0, 0xda, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d,
	0x6e, 0x23, 0x5e, 0xb0, 0x29, 0x6e, 0x99, 0xa9, 0x39, 0x29, 0xae, 0x45, 0x45, 0x41, 0x50, 0x49,
	0x25, 0x0b, 0x2e, 0x0e, 0x98, 0x98, 0x90, 0x08, 0x17, 0x6b, 0x1a, 0x88, 0x0d, 0x35, 0x0a, 0xc2,
	0x11, 0x12, 0x43, 0x31, 0x88, 0x13, 0xa6, 0x33, 0x89, 0x0d, 0xec, 0x25, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfd, 0x23, 0xc2, 0x1c, 0xdf, 0x00, 0x00, 0x00,
}
